import globals from "globals";
import tseslint from "@typescript-eslint/eslint-plugin"; // Flat config
import tseslintParser from "@typescript-eslint/parser";

export default [
  {
    ignores: ["dist", "node_modules", "coverage", "llm-context"],
  },
  {
    files: ["**/*.ts"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.node,
      },
      parser: tseslintParser,
      parserOptions: {
        project: "./tsconfig.json",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
    },
    rules: {
      // Error prevention
      "@typescript-eslint/no-unused-vars": "warn",
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/require-await": "warn",
      "no-await-in-loop": "error",
      "no-constant-condition": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-empty": "warn",
      "no-empty-pattern": "error",
      "no-eval": "error",
      "no-ex-assign": "error",
      "no-extra-semi": "error",
      "no-func-assign": "error",
      "no-import-assign": "error",
      "no-invalid-regexp": "error",
      "no-loss-of-precision": "error",
      "no-redeclare": "error",
      "no-regex-spaces": "error",
      "no-setter-return": "error",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-private-class-members": "warn",
      "no-useless-backreference": "error",
      
      // Best practices
      "accessor-pairs": "error",
      "array-callback-return": "error",
      "consistent-return": "warn",
      "default-case": "warn",
      "default-case-last": "error",
      "default-param-last": "error",
      "grouped-accessor-pairs": "error",
      "no-else-return": "error",
      "no-empty-function": "warn",
      "no-eq-null": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-label": "error",
      "no-fallthrough": "error",
      "no-global-assign": "error",
      "no-native-reassign": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-octal": "error",
      "no-octal-escape": "error",
      "no-param-reassign": "error",
      "no-proto": "error",
      "no-script-url": "error",
      "no-shadow": "warn",
      "no-throw-literal": "error",
      "no-undef-init": "error",
      "no-unmodified-loop-condition": "error",
      "no-unused-expressions": "error",
      "no-unused-labels": "error",
      "no-useless-call": "error",
      "no-useless-catch": "error",
      "no-useless-computed-key": "error",
      "no-useless-constructor": "warn",
      "no-useless-escape": "warn",
      "no-useless-rename": "error",
      "no-useless-return": "warn",
      "no-var": "error",
      "object-shorthand": "error",
      "prefer-const": "error",
      "prefer-exponentiation-operator": "error",
      "prefer-named-capture-group": "warn",
      "prefer-object-has-own": "error",
      "prefer-regex-literals": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      "require-unicode-regexp": "warn",
      "rest-spread-spacing": "error",
      "semi": ["error", "always"],
      "semi-spacing": "error",
      "semi-style": "error",
      "sort-keys": "off",
      "sort-vars": "off",
      "strict": "off",
      "use-isnan": "error",
      "valid-typeof": "error",
    },
  },
];